console.log('\n\n\n\n\n\n\n');

// require('./binary-gap');
// require('./brackets');
// require('./change-calculation');
// require('./collect-cards');
// require('./count-div');
// require('./cyclic-rotation');
// require('./decimal-representation');
// require('./distinct');
// require('./find-word');
// require('./frog-jmp');
// require('./frog-river-one');
// require('./max-counters');
// require('./max-product-of-three');
// require('./max-slice-sum');
// require('./minimum-hits');
// require('./min-avg-two-slice');
// require('./missing-integer');
require('./multiplies-3-5');
// require ('./odd-occurence-in-array');
// require ('./passing-cars');
// require ('./perm-check.js');
// require ('./perm-missing-elements');
// require('./reordering-groups');
// require('./stone-wall');
// require('./tape-equilibrium');
// require('./triangle');

console.log('\n\n\n\n\n\n\n\n\n\n\n');