// import './binary-gap';
// import './brackets';
// import './distinct';
// import './change-calculation';
// import './collect-cards';
// import './cyclic-rotation';
// import './frog-jmp';
import './frog-river-one';
// import './max-counters';
// import './max-slice-sum';
// import './missing-integer';
// import './perm-check';
// import './perm-missing-elements';
// import './tape_equilibrium';
